### ISSUE TITLE
Allow the result of a given check to be stored and re-used in a further test

### ISSUE THREAD

**Issue by andreamoro** [testomato/help.testomato.com#1]
Test concatenation would be a nice feature for your product so to satisfy the most complex scenarios.

For instance, as of today using the HTML on Page it is possible to validate the presence of a canonical tag, but if I want to validate whether I've a self-canonical or a canonicalised URL it's impossible.

Having a test-unit that returns a result in a variable that can be referenced later on would allow doing so.

**Comment by OzzyCzech** [comment]
Thank's for suggestion, but we do not have any future plan to add this functionality to the Testomato
