### ISSUE TITLE
REG: Issue with one particular website status shows intermittent failure.

### ISSUE THREAD

**Issue by jwnmohan** [testomato/help.testomato.com#3]
Hi Team,

REG: Issue with one particular website status shows failure sometime and sometimes up and running 

We need some advise here , We have many websites has been monitored under Testomato. But one particular website recent being its just shows always failure in Dashboard . Website is up and running. We would like to know how to proceed further. 

There is in Firewall blocking for Testomato IP's. We have checked the logs and we could see at some hits of website shows status code 200 and sometimes 403 error.

There is no ip or packet drops .

**Comment by OzzyCzech** [comment]
Hi @jwnmohan,

Please send us an email to support@testomato.com with a link to the project, we will check if Testomato sends any request to your website and what we get back from you.

Roman

**Comment by jwnmohan** [comment]
Hi OzzyCzech,

Thanks a lot for your reply !!!

With those information i already sent an email to the support@testomato.com . Please check and confirm

**Comment by OzzyCzech** [comment]
I can confirm, thank you, we'll look into it
